config/routes.rb
Internations::Application.routes.draw do
  resources :groups

  resources :users

  root :to => 'users#index'

  

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
	has_and_belongs_to_many :groups

	
  def group?(group_name)
  	group = Group.find_by_sql("select * from users u, groups_users gu, groups g 
  		where u.id = gu.user_id and g.id = gu.group_id and u.id = '#{self.id}' and g.name = '#{group_name}'")
  	if !group.blank?
  		return true
  	else 
  		return false
  	end
  end

	def add_group(group_name)
    unless group_name.nil?
      if ((self.group?(group_name)) == false)
        group = Group.find_by_name(group_name)
        if !group.blank?
        	group.users << self
        	notice = "The user has been successfully added to the group."
        end
       else
       	 notice = "The user is already part of the group."
      end
    end
    return notice
  end
  
  def remove_group(group_name)
    unless group_name.nil?
      if self.group?(group_name)
      	g = Group.find_by_name(group_name)
        self.groups.delete(g)
        notice = "The user has been successfully removed from the group."
      end
    end
    return notice
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
    if params[:edit]
      @users = User.find_by_sql("select u.* from groups g, groups_users gu, users u where gu.group_id = g.id and gu.user_id = u.id and g.id = '#{@group.id}'")
    end
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    if params[:user_name]
      logger.debug "in add users"
      @user = User.find_by_name(params[:user_name])
      if @user
        notice = @user.add_group(@group.name)
      else
        notice = "There is no user by that name."
      end
      flash[:notice] = notice
      redirect_to edit_group_url(@group, :edit => "add_users")
    elsif params[:edit] == "remove_users"
      logger.debug "in remove users"
      @user = User.find(params[:user_id])
      notice = @user.remove_group(@group.name)
      flash[:notice] = notice
      redirect_to edit_group_url(@group, :edit => "remove_users")
    else
      respond_to do |format|
        if @group.update(group_params)
          logger.debug "Updating group data"
          format.html { redirect_to @group, notice: 'Group was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @group.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    if @group.users
      flash[:notice] = "I'm sorry, this group still has users and cannot be deleted."
    else
      @group.destroy
    end
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description)
    end

    def edit_params
      params.permit(:user_name)
      params.permit(:edit)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<div class="form-group">
  <%= form_for(@group) do |f| %>
    <% if @group.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

        <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, :class => "form-control" %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description, :class => "form-control" %>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  <% end %>
</div>

app/views/groups/edit.html.erb
<div class="container">
	<% if params[:edit] %>
		<h1> Add Users to Group <%= @group.name %></h1>
		<div class="form-group">
			<%= form_tag(url_for(:action => "update", :controller => "groups"), :method => :put) do %>
				<%= label_tag :user_name, 'Name:' %>
		    <%= text_field_tag 'user_name', nil, class: 'form-control' %>
		    <%= hidden_field_tag "group[name]", @group.name %> 
		    <br />
    		<button type="submit" class="btn btn-primary">Submit</button>
		</div>
		<% end %> 

		<h2> Users </h2>
		<table class="table table-striped">
			<thead>
		    <tr>
		      <th>Name</th>
		      <th>Admin</th>
		      <th></th>
		    </tr>
	  	</thead>
			<% @users.each do |u| %>
			   <tr>
	        <td><%= u.name %></td>
	        <td><%= u.admin %></td>
	        <td><%= link_to 'Remove from Group', group_url(@group, :edit => "remove_users", :user_id => u.id), :method => :put %></td>
	      </tr>
			<% end %>
		</table>
	<% else %>
		<h1>Editing group</h1>

		<%= render 'form' %>

		<%= link_to 'Show', @group %> |
		<%= link_to 'Back', groups_path %>
	<% end %>
</div>

app/views/groups/index.html.erb
<div class="container">
  <h1>Groups</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td><%= group.name %></td>
          <td><%= group.description %></td>
          <td><%= link_to 'Add Users', edit_group_path(group, :edit => "add_users") %></td>
          <td><%= link_to 'Show', group %></td>
          <td><%= link_to 'Edit', edit_group_path(group) %></td>
          <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Group', new_group_path, :class => "btn btn-primary" %>
</div>

app/views/groups/new.html.erb
<div class="container">
	<h1>New group</h1>

	<%= render 'form' %>

	<%= link_to 'Back', groups_path %>
</div>

app/views/groups/show.html.erb
<div class="container">
	<p>
	  <strong>Name:</strong>
	  <%= @group.name %>
	</p>

	<p>
	  <strong>Description:</strong>
	  <%= @group.description %>
	</p>

	<%= link_to 'Edit', edit_group_path(@group) %> |
	<%= link_to 'Back', groups_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Internations</title>
  <%= stylesheet_link_tag 'bootstrap-theme.min' %>
  <%= stylesheet_link_tag 'bootstrap.min' %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "bootstrap.min" %>
  <%= javascript_include_tag "jquery-1.11.1.min" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<nav class="navbar navbar-default" role="navigation">
<div class="container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "InterNations", users_url, :class => "navbar-brand" %>
  </div>
  <div id="navbar" class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to "Users", users_url %></li>
      <li><%= link_to "Groups", groups_url %></li>
    </ul>
  </div><!--/.nav-collapse -->
</div><!--/.container-fluid -->
</nav>
<body>
	<% flash.each do |name, msg| -%>
	<div class="alert alert-warning">
    <%= content_tag :div, msg, class: name %>
	</div>
	<% end -%>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<div class="form-group">
  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, :class => "form-control" %>
    </div>
    <div class="field">
      <%= f.label :admin %><br>
      <%= f.check_box :admin %>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
	<h1>Editing user</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @user %> |
	<%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<div class="container">
  <h1>Users</h1>
  <p> Welcome, admins. Please create and delete users below. </p>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Admin</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.admin %></td>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New User', new_user_path, :class => "btn btn-primary" %>
</div>

app/views/users/new.html.erb
<div class="container">
	<h1>New user</h1>

	<%= render 'form' %>

	<%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<div class="container">
	<p>
	  <strong>Name:</strong>
	  <%= @user.name %>
	</p>

	<p>
	  <strong>Admin:</strong>
	  <%= @user.admin %>
	</p>

	<%= link_to 'Edit', edit_user_path(@user) %> |
	<%= link_to 'Back', users_path %>
</div>